### PR TITLE
Feature: Setting the start position

### PR DESCRIPTION
**Pull request by spaluchiewicz**
This PR is to solve #20 (Setting the start position)

### CODE REVIEW

**Comment by spaluchiewicz** [comment]
@HamzaGhazouani will you be able to review and approve this PR?

**Comment by HamzaGhazouani** [comment]
Hi @spaluchiewicz, thanks for your contribution, I will look at it soon, it will be nice if we add an example of this feature in the sample

**Comment by spaluchiewicz** [comment]
Sure, I will update the PR.

**Comment by iblagajic** [comment]
Hi, can I help wrap this up?

**Comment by HamzaGhazouani** [comment]
Hi @iblagajic, 
you can checkout @spaluchiewicz branch's, and if you can do the modifications in my comment above it will be perfect, thanks a lot

**Comment by iblagajic** [comment]
Should I create a new PR or can I contribute to the existing one?

**Comment by HamzaGhazouani** [comment]
@iblagajic as you prefer :)

**Pull request closed without merging**
